### ISSUE TITLE
Double tap sensing

### ISSUE THREAD

**Issue by yusaira-khan** [ShivanKaul/STEmbedded#5]
- calibrate?
- kalman?
- debouncing? 
- cats

**Comment by deepaks4077** [comment]
Wrote matlab script which calculated the mean and stdd of filtered and calibrated values. Can be used to tweak a constant multiplicative factor for the stdd to classify a single TAP. Still need to detect a double TAP.

Options are:
1. Have a low and high threshold. Double tap detected in between. @yusaira-khan can you explain a little more?
2. Detect the increase in magnitude across time. So set a flag and start a counter for the next few accelerometer values. If they all pass a threshold (may be different than the first threshold?) then double tap is set to true. Otherwise, reset counter and flag.

**Comment by yusaira-khan** [comment]
:corn:
